Add cloudformation template for pattern-1 with puppet.
wso2/cloudformation-is pull request #3
Opened 2017-12-04 10:56 UTC by malithie

## Purpose
This adds a cloudformation template for WSO2 Identity Server single node deployment with external datasources.
Deployment is done over a puppet master agent setup.

## Test environment
JDK: jdk-8u131 
DataSource: MYSQL
WSO2 IS 5.4.0

2017-12-04 11:39 UTC, chamilad requested changes

2017-12-04 11:39 UTC, chamilad commented on cloudformation-templates/pattern-1/pattern-1-with-puppet-cloudformation.template.yml
> +        CidrIp: 0.0.0.0/0
Is it required to open all ports to outside for the instance security groups?

2017-12-04 11:39 UTC, chamilad commented on cloudformation-templates/pattern-1/pattern-1-with-puppet-cloudformation.template.yml
> +          CidrIp: 0.0.0.0/0
Isn't it better to restrict this to connections from the instance security group?

2017-12-04 13:32 UTC, chamilad approved these changes
After an offline discussion with @malithie it was decided to push the suggested changes to a later PR for the purpose of ease of testing.

2017-12-04 18:20 UTC, malithie commented
Fixed review comments from @chamilad

2017-12-05 10:24 UTC, isharak approved these changes

2017-12-05 10:29 UTC, merged